### ISSUE TITLE
i get shadowRoot is undefined

### ISSUE THREAD

**Issue by dzmitry-lahoda** [kaczor6418/web-assembly-rust-typescript-template#7]

**Comment by kaczor6418** [comment]
Hi Can you provide additional information? For example, your os webrowser which you have used? For me, that works fine, and I do not get any errors?

**Comment by dzmitry-lahoda** [comment]
i took example, run it, and got undefined error. when i set shadow directly, it worked. it is on windows 10 latee firefox version.

**Comment by kaczor6418** [comment]
I have checked on Windows 10 + the latest Firefox and that works too:
![image](https://user-images.githubusercontent.com/34687242/133943338-3b04b514-48ab-4f4b-ab9a-dae83b7f9640.png)

**Comment by dzmitry-lahoda** [comment]
hm. will recheck
